"""Add phone number to users table

Revision ID: a689f29393c6
Revises: 51e7443b9c56
Create Date: 2024-11-30 05:28:37.111636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a689f29393c6'
down_revision: Union[str, None] = '51e7443b9c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_nmber', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_nmber')
    # ### end Alembic commands ###
