name: Pylint

on:
  workflow_dispatch: # This enables manual triggering of the workflow
  push:
    paths-ignore:
      - ".github/workflows/*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.3

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.12.3-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.12.3-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analyze the code with pylint
        run: |
          pylint $(git ls-files '*.py') --exit-zero > pylint_report.txt

      - name: Debug Workspace
        run: ls -la

      - name: Debug Pylint Report Content
        run: cat pylint_report.txt

      - name: Install bc
        run: choco install bc -y

      - name: Check Pylint Score
        shell: bash
        run: |
          score=$(grep -oP 'Your code has been rated at \K\d+\.\d+' pylint_report.txt || echo "0")
          echo "Pylint score: $score"
          threshold=8.0
          if (( $(echo "$score > $threshold" | bc -l) )); then
            echo "Pylint score ($score) meets the threshold ($threshold)"
          else
            echo "Pylint score ($score) does not meet the threshold ($threshold)"
            exit 1
          fi
