name: Pylint

on:
  push:
    # Ignore changes to any files in .github/workflows (workflow files themselves)
    paths-ignore:
      - '.github/workflows/*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        pip install pylint  # Install pylint separately if not in requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
