name: Pylint

on:
  push:
    # Ignore changes to any files in .github/workflows (workflow files themselves)
    paths-ignore:
      - ".github/workflows/*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.3 # Specify a single Python version

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip # Cache pip's package directory
          key: ${{ runner.os }}-pip-3.12.3-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.12.3-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt
          pip install pylint  # Install pylint separately if not in requirements.txt

      - name: Analyzing the code with pylint
        run: |
          pylint $(git ls-files '*.py')  # Run pylint on Python files
